plugins {
    id("java-library")
    id("checkstyle")
    alias(libs.plugins.maven.publish)
}

group = "org.komamitsu"
version = "3.0.0-SNAPSHOT"
description = "Jackson 3.x extension that adds support for MessagePack"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    api(libs.jackson.databind)
    api(libs.msgpack.core)

    testImplementation(libs.junit.jupiter)
    testImplementation(libs.hamcrest)
    testImplementation(libs.commons.math3)
    testRuntimeOnly(libs.junit.platform.launcher)
}

// PackageVersion.java carries the coordinates and version Jackson reports via Versioned.
// Generate it from the Gradle project so it cannot drift from the published POM.
val packageDir = "org/komamitsu/jackson/dataformat/msgpack"
val generatePackageVersion by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/sources/packageVersion/java/main")
    val projectVersion = project.version.toString()
    val projectGroup = project.group.toString()
    val projectName = project.name
    inputs.property("version", projectVersion)
    outputs.dir(outputDir)
    doLast {
        val (major, minor, patch, snapshot) = Regex("""(\d+)\.(\d+)\.(\d+)(?:-(.+))?""")
            .matchEntire(projectVersion)!!.destructured
        val snapshotInfo = if (snapshot.isEmpty()) "null" else "\"$snapshot\""
        val file = outputDir.get().file("$packageDir/PackageVersion.java").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package ${packageDir.replace('/', '.')};
            |
            |import tools.jackson.core.Version;
            |import tools.jackson.core.Versioned;
            |
            |// Generated by the Gradle build from the project version. Do not edit.
            |public class PackageVersion
            |        implements Versioned
            |{
            |    public static final Version VERSION = new Version($major, $minor, $patch, $snapshotInfo, "$projectGroup", "$projectName");
            |
            |    @Override
            |    public Version version()
            |    {
            |        return VERSION;
            |    }
            |}
            |""".trimMargin()
        )
    }
}

sourceSets.main {
    java.srcDir(generatePackageVersion)
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.compilerArgs.addAll(listOf("-Xlint:unchecked", "-Xlint:deprecation"))
}

tasks.withType<Javadoc>().configureEach {
    (options as StandardJavadocDocletOptions).addBooleanOption("Xdoclint:none", true)
}

// Compilation is pinned to 17 above; tests can run on a newer JDK with -PtestJavaVersion=21.
val testJavaVersion = providers.gradleProperty("testJavaVersion").map(JavaLanguageVersion::of)

tasks.test {
    useJUnitPlatform()
    jvmArgs("-ea")
    if (testJavaVersion.isPresent) {
        javaLauncher = javaToolchains.launcherFor { languageVersion = testJavaVersion }
    }
    testLogging {
        events("failed")
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
    }
}

checkstyle {
    toolVersion = "10.21.1"
    configFile = file("config/checkstyle/checkstyle.xml")
    maxWarnings = 0
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()

    pom {
        name = project.name
        description = project.description
        url = "https://github.com/komamitsu/jackson-dataformat-msgpack"
        licenses {
            license {
                name = "Apache-2.0"
                url = "https://www.apache.org/licenses/LICENSE-2.0.txt"
            }
        }
        developers {
            developer {
                id = "komamitsu"
                name = "Mitsunori Komatsu"
                email = "komamitsu@gmail.com"
                url = "https://github.com/komamitsu"
            }
        }
        scm {
            url = "https://github.com/komamitsu/jackson-dataformat-msgpack"
            connection = "scm:git:git://github.com/komamitsu/jackson-dataformat-msgpack.git"
            developerConnection = "scm:git:ssh://git@github.com/komamitsu/jackson-dataformat-msgpack.git"
        }
    }
}
